/**
 * Drive DRISHTI-G with months of plausible municipal traffic.
 *
 *   npm run sim:run -- --days 180 --per-day 30 --seed 42
 *
 * Why this is not a database seeder
 * ---------------------------------
 * The system's interesting behaviour is not in its tables, it is in what the
 * engines do when work arrives: GCCE reads the text and picks a department, the
 * priority engine scores urgency, the clustering engine notices that eleven
 * people reported the same choked drain, the scheduler escalates what nobody
 * touched, GRIE scores the units that keep missing deadlines. A seeder that
 * writes rows produces a database that *looks* like all of that happened and a
 * system that has never actually done any of it.
 *
 * So every action here goes through the real HTTP API, as the real actor, with
 * a real session cookie. A synthetic citizen registers and files; the officer
 * GCCE actually chose logs in and issues a work order; a crew member opens the
 * code with no account at all and reports the job done; the officer inspects
 * it. Nothing is written on their behalf. If routing is broken, this run fails
 * the way a user would experience it being broken.
 *
 * The one exception, stated plainly
 * ---------------------------------
 * Timestamps. The API stamps `now()` on everything, and six months of work that
 * all happened this afternoon is useless for a log whose whole purpose is
 * elapsed time. After the API has finished with a case, `lib/sim-clock.ts`
 * rewrites its timestamps onto the simulated schedule. **Every row's existence
 * and content is real; its timestamp is fiction.** That module is env-gated and
 * refuses to run in production; see its header for the reasoning.
 *
 * What this data may and may not be used for
 * ------------------------------------------
 * It may train the in-system classifier, predictor and SLA estimator, fill the
 * screens, and demonstrate the engines running. It is **not evidence for any
 * claim in either paper** — it is generated by the same system it would be used
 * to evaluate, which is circular. See docs/pending-work.md and
 * docs/research-decisions.md.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { PrismaClient } from '@prisma/client'
import { Rng } from './lib/sim-random.js'
import { ApiError, Session, waitForApi } from './lib/sim-http.js'
import { syntheticPhoto } from './lib/sim-image.js'
import {
  CREW_NOTES,
  OVERRIDE_REASONS,
  REJECTION_NOTES,
  TEMPLATES,
  type ComplaintTemplate,
} from './lib/sim-catalogue.js'
import {
  assertTimeTravelAllowed,
  repairEscalatedDeadlines,
  reschedule,
  rescheduleSweepOutput,
  type CaseSchedule,
} from './lib/sim-clock.js'
import * as org from '../src/services/orgTree.js'

/** Written into the labels CSV; kept as a constant so no escape survives an edit. */
const LINE_END = String.fromCharCode(10)

const HOUR = 3_600_000
const DAY = 24 * HOUR

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

interface Options {
  days: number
  perDay: number
  breachRate: number
  overrideRate: number
  seed: number
  baseUrl: string
  citizens: number
  password: string
  /** Clear the previous simulation before running, so the seed reproduces. */
  reset: boolean
}

/** Synthetic residents are recognisable by address, and nothing else is. */
const SIM_EMAIL_PREFIX = 'sim.'
const SIM_EMAIL_DOMAIN = '@residents.example'

function parseOptions(argv: string[]): Options {
  const flags = new Map<string, string>()
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i]!
    if (!token.startsWith('--')) continue
    const [name, inline] = token.slice(2).split('=')

    if (inline !== undefined) {
      flags.set(name!, inline)
      continue
    }

    // A valueless flag must not swallow the one after it. `--reset --days 5`
    // consumed `--days` as reset's value in the first version, so `days` fell
    // back to its default of 180 and a five-day smoke test quietly filed 1,626
    // complaints. Only take the next token if it is not itself a flag.
    const next = argv[i + 1]
    if (next !== undefined && !next.startsWith('--')) {
      flags.set(name!, next)
      i++
    } else {
      flags.set(name!, '')
    }
  }

  const number = (name: string, fallback: number): number => {
    const raw = flags.get(name)
    if (raw === undefined) return fallback
    const value = Number(raw)
    if (!Number.isFinite(value)) throw new Error(`--${name} must be a number, got ${raw}`)
    return value
  }

  return {
    days: number('days', 180),
    perDay: number('per-day', 30),
    breachRate: number('breach-rate', 0.15),
    overrideRate: number('override-rate', 0.1),
    seed: number('seed', 20260909),
    citizens: number('citizens', 120),
    baseUrl: flags.get('base-url') ?? 'http://localhost:4000/api/v1',
    password: flags.get('password') ?? 'drishti123',
    reset: flags.has('reset'),
  }
}

// ---------------------------------------------------------------------------
// The authority, as the simulator needs to see it
// ---------------------------------------------------------------------------

interface Officer {
  id: number
  email: string
  fullName: string
  session?: Session
}

interface CrewMember {
  id: number
  /** The API nests it; flattened on the way in so the filter below reads plainly. */
  sector: { id: number } | null
}

interface Catalogue {
  units: { id: number; name: string; isLeaf: boolean }[]
  officers: Map<number, Officer>
  crewByOfficer: Map<number, CrewMember[]>
}

/**
 * Read the authority through the console, as a Super Admin would.
 *
 * Deliberately not read from Prisma: if the console cannot describe the
 * authority, the simulator should fail here rather than quietly produce traffic
 * against a shape the API disagrees with.
 */
async function loadCatalogue(admin: Session): Promise<Catalogue> {
  const staff = await admin.get<{
    items: { id: number; email: string; fullName: string; rank: string }[]
  }>('/console/staff?size=100&rank=SECTION_OFFICER')

  const officers = new Map<number, Officer>()
  for (const person of staff.items) {
    if (person.rank === 'SECTION_OFFICER') {
      officers.set(person.id, { id: person.id, email: person.email, fullName: person.fullName })
    }
  }

  return { units: await walkTree(admin), officers, crewByOfficer: new Map() }
}

/**
 * Flatten the org tree by walking it from the root.
 *
 * There is no flat-list endpoint — the console drills down one unit at a time,
 * which is right for the screen and awkward here. Walking it is a handful of
 * requests against a tree twenty-odd units wide, and it keeps the simulator
 * reading the authority through the same API everything else uses.
 */
async function walkTree(admin: Session): Promise<Catalogue['units']> {
  const { rootId } = await admin.get<{ rootId: number }>('/console/units')
  const units: Catalogue['units'] = []
  const queue = [rootId]
  const seen = new Set<number>()

  while (queue.length > 0) {
    const id = queue.shift()!
    if (seen.has(id)) continue
    seen.add(id)

    const detail = await admin.get<{
      unit: { id: number; name: string; isLeaf: boolean }
      children: { id: number; name: string; isLeaf: boolean }[]
    }>(`/console/units/${id}`)

    units.push(detail.unit)
    for (const child of detail.children ?? []) queue.push(child.id)
  }

  return units
}

// ---------------------------------------------------------------------------
// Simulated people
// ---------------------------------------------------------------------------

const FIRST = [
  'Aarti', 'Rohit', 'Sunita', 'Imran', 'Kavita', 'Deepak', 'Meena', 'Suresh', 'Neha', 'Rakesh',
  'Pooja', 'Vikas', 'Anjali', 'Manoj', 'Shalini', 'Naveen', 'Preeti', 'Sanjay', 'Ritu', 'Ajay',
]
const LAST = [
  'Sharma', 'Verma', 'Gupta', 'Singh', 'Yadav', 'Khan', 'Chauhan', 'Mishra', 'Tyagi', 'Nagar',
  'Bhati', 'Kumar', 'Saini', 'Rana', 'Joshi',
]

/**
 * Bring the synthetic residents online, registering them the first time.
 *
 * Addresses are derived from the seed, not from the clock, so the same seed
 * addresses the same people every run. An account that already exists is signed
 * into rather than recreated — accounts are never deleted between runs, because
 * deleting a user nulls `AuditEvent.actorId` and breaks the hash chain for
 * everything they ever did.
 */
async function registerCitizens(
  options: Options,
  rng: Rng,
  units: { id: number; isLeaf: boolean }[],
): Promise<Session[]> {
  const leaves = units.filter((u) => u.isLeaf)
  const homes = leaves.length > 0 ? leaves : units
  const sessions: Session[] = []
  let reused = 0

  for (let i = 0; i < options.citizens; i++) {
    const fullName = `${rng.pick(FIRST)} ${rng.pick(LAST)}`
    const email = `${SIM_EMAIL_PREFIX}${options.seed}.${i}${SIM_EMAIL_DOMAIN}`
    const session = new Session(options.baseUrl, fullName)

    try {
      await session.post('/auth/register', {
        email,
        password: options.password,
        fullName,
        homeUnitId: homes.length > 0 ? rng.pick(homes).id : null,
      })
      sessions.push(session)
    } catch (error) {
      if (!(error instanceof ApiError) || error.status !== 409) throw error
      // Already exists from an earlier run — sign in instead.
      try {
        await session.post('/auth/login', { email, password: options.password })
        sessions.push(session)
        reused++
      } catch {
        // An account at this address exists with a different password; skip it.
      }
    }
  }

  if (sessions.length === 0) throw new Error('Could not bring any synthetic residents online.')
  if (reused > 0) console.log(`  (${reused} of them already existed and were signed in)`)
  return sessions
}

async function officerSession(officer: Officer, options: Options): Promise<Session | null> {
  if (officer.session) return officer.session
  const session = new Session(options.baseUrl, officer.fullName)
  try {
    await session.post('/auth/login', { email: officer.email, password: options.password })
  } catch {
    // A seeded officer whose password differs from the demo one simply cannot
    // act; their complaints stay unallotted, which is a realistic vacancy.
    return null
  }
  officer.session = session
  return session
}

// ---------------------------------------------------------------------------
// One complaint's life
// ---------------------------------------------------------------------------

/** Everything decided about a case before any request is made. */
/**
 * When each step of a case happened, in simulated time.
 *
 * A field is present only if that step falls **before now**. That is what keeps
 * the register honest at the recent end of the window: a complaint filed
 * yesterday whose natural timeline runs five days cannot already be resolved,
 * so it simply has no `settledAt` and the simulator stops driving it there.
 *
 * Without this the log ran days into the future — the first version resolved
 * complaints on dates that had not happened yet, which every downstream
 * consumer would read as real and none would flag.
 *
 * The side effect is the right one: the window ends with a natural mix of
 * in-flight work at every stage, which is what a live register looks like and
 * what the officer desk and the sweeps need in order to have anything to do.
 */
interface Timeline {
  filedAt: Date
  routedAt?: Date
  allottedAt?: Date
  submittedAt?: Date
  rejectedAt?: Date
  resubmittedAt?: Date
  /** Officer accepted, or the citizen confirmed. */
  settledAt?: Date
  closedAt?: Date
}

interface Plan {
  filedAt: Date
  template: ComplaintTemplate
  phrasing: { title: string; description: string }
  /** Nobody touches it and it blows its deadline. */
  breach: boolean
  /** The control room moves it away from where GCCE sent it. */
  override: boolean
  /** The officer sends the first submission back. */
  rejectOnce: boolean
  /** The citizen answers the "is it fixed?" question. */
  confirms: boolean
  /** The citizen answers the confirmation prompt at all. */
  answersCategory: boolean
  /** Having answered, they disagree. */
  correctsCategory: boolean
  timeline: Timeline
}

/** The simulated moments, oldest first, for rewriting the case's rows. */
function momentsOf(timeline: Timeline): Date[] {
  return [
    timeline.routedAt,
    timeline.allottedAt,
    timeline.submittedAt,
    timeline.rejectedAt,
    timeline.resubmittedAt,
    timeline.settledAt,
    timeline.closedAt,
  ].filter((moment): moment is Date => moment != null)
}

const MONSOON_MONTHS = new Set([6, 7, 8]) // July, August, September

function pickTemplate(rng: Rng, when: Date): ComplaintTemplate {
  const monsoon = MONSOON_MONTHS.has(when.getMonth())
  return rng.weighted(
    TEMPLATES.map((t) => ({
      value: t,
      weight: t.weight * (monsoon && t.monsoon ? t.monsoon : 1),
    })),
  )
}

function plan(rng: Rng, filedAt: Date, options: Options, now: number): Plan {
  const template = pickTemplate(rng, filedAt)
  const breach = rng.chance(options.breachRate)
  const rejectOnce = !breach && rng.chance(0.12)

  // Delays compound: each stage begins when the last one ended. Log-normal
  // rather than uniform because these all have a floor and a long tail — most
  // officers get to a job the same day, a few take a fortnight, and it is the
  // tail that produces a believable breach rate rather than a flat one.
  const timeline: Timeline = { filedAt }
  let cursor = filedAt.getTime()

  /** Advance the clock, and record the step only if it has actually happened. */
  const step = (ms: number): Date | undefined => {
    cursor += Math.max(ms, 60_000)
    return cursor <= now ? new Date(cursor) : undefined
  }

  timeline.routedAt = step(rng.float(2, 30) * 60_000)

  if (!breach) {
    timeline.allottedAt = step(rng.logNormal(8 * HOUR, 0.9))
    timeline.submittedAt = step(rng.logNormal(20 * HOUR, 0.8))
    if (rejectOnce) {
      timeline.rejectedAt = step(rng.logNormal(10 * HOUR, 0.7))
      timeline.resubmittedAt = step(rng.logNormal(18 * HOUR, 0.7))
    }
    timeline.settledAt = step(rng.logNormal(12 * HOUR, 0.9))
    timeline.closedAt = step(rng.logNormal(24 * HOUR, 1.0))
  }

  return {
    filedAt,
    template,
    phrasing: rng.pick(template.phrasings),
    breach,
    override: rng.chance(options.overrideRate),
    rejectOnce,
    confirms: rng.chance(0.62),
    // Roughly half answer the prompt; of those, about one in eight disagrees.
    answersCategory: rng.chance(0.45),
    correctsCategory: rng.chance(0.12),
    timeline,
  }
}

/**
 * What each complaint was really about, independent of what GCCE decided.
 *
 * The one label in this dataset that is not the keyword matcher's own opinion.
 * Training a classifier on GCCE's assignments would teach it to imitate the
 * matcher it is meant to replace, and "beats the keyword baseline" would be
 * meaningless — the model would have learned the baseline. Citizen corrections
 * are genuine supervision but there are only a few dozen of them.
 *
 * So the simulator writes down which template produced each complaint. That is
 * real ground truth *for this dataset*, and it exists only because the dataset
 * was generated. Any accuracy measured against it demonstrates that the
 * training pipeline works; it is not evidence about municipal text, and
 * research/data/README explains why at the point of use.
 */
interface GroundTruth {
  referenceNo: string
  category: string
}

interface Tally {
  filed: number
  routed: number
  allotted: number
  submitted: number
  rejected: number
  resolved: number
  confirmed: number
  overridden: number
  categoryCorrected: number
  categoryConfirmed: number
  leftToBreach: number
  /** Crew reported done, nobody answered — the verification sweep's caseload. */
  leftUnanswered: number
  /** The automated proof checks refused the evidence, so the job stayed open. */
  proofRefused: number
  /** Refused by the public rate limiter on the crew surface. */
  rateLimited: number
  failures: Map<string, number>
}

function note(tally: Tally, message: string): void {
  tally.failures.set(message, (tally.failures.get(message) ?? 0) + 1)
}

/**
 * File one complaint and walk it as far as its plan says it should go.
 *
 * Returns the schedule its rows should be rewritten onto, or null if the case
 * never made it far enough to be worth rescheduling.
 */
async function runCase(
  plan: Plan,
  citizen: Session,
  admin: Session,
  catalogue: Catalogue,
  options: Options,
  rng: Rng,
  tally: Tally,
  truth: GroundTruth[],
): Promise<CaseSchedule | null> {
  // The serializer nests the references rather than exposing raw foreign keys,
  // so this mirrors `publicComplaint` rather than the Prisma row.
  let filed: {
    complaint: {
      id: number
      referenceNo: string
      status: string
      slaDueAt: string | null
      assignedOfficer: { id: number } | null
      sector: { id: number } | null
      category: { id: number } | null
    }
  }

  try {
    filed = await citizen.post('/complaints', {
      title: plan.phrasing.title,
      description: plan.phrasing.description,
      // Noida sits around 28.57 N, 77.32 E. Spread reports across it so the
      // map and the clustering engine both have something to work with.
      latitude: rng.float(28.49, 28.63),
      longitude: rng.float(77.27, 77.42),
      isCommunity: rng.chance(0.22),
    })
  } catch (error) {
    note(tally, error instanceof ApiError ? `file: ${error.status}` : 'file: threw')
    return null
  }

  const complaint = filed.complaint
  tally.filed++
  truth.push({ referenceNo: complaint.referenceNo, category: plan.template.category })
  if (complaint.assignedOfficer != null) tally.routed++

  const schedule: CaseSchedule = {
    complaintId: complaint.id,
    filedAt: plan.filedAt,
    transitions: momentsOf(plan.timeline),
    slaDueAt: null,
    resolvedAt: null,
    closedAt: null,
    issuedAt: plan.timeline.allottedAt ?? null,
    submittedAt: plan.timeline.resubmittedAt ?? plan.timeline.submittedAt ?? null,
  }

  // The deadline is GCCE's, kept as an offset from filing so the simulated
  // clock preserves how much time the officer was actually given.
  if (complaint.slaDueAt) {
    const granted = new Date(complaint.slaDueAt).getTime() - Date.now()
    schedule.slaDueAt = new Date(plan.filedAt.getTime() + granted)
  }

  /*
   * The citizen answers "we sent this to Electrical — is that right?"
   *
   * Both answers are driven, and that matters more than it looks. The first
   * version only ever sent corrections, so every label in the decision table
   * was one of the classifier's mistakes and the agreement rate read 0% — not
   * because the engine was always wrong, but because being right was
   * unrepresentable. Most real citizens confirm.
   */
  if (plan.answersCategory && complaint.category) {
    const corrects = plan.correctsCategory
    try {
      await citizen.post(`/complaints/${complaint.id}/category`, {
        categoryId: corrects ? null : complaint.category.id,
      })
      if (corrects) tally.categoryCorrected++
      else tally.categoryConfirmed++
    } catch (error) {
      note(tally, error instanceof ApiError ? `category: ${error.status}` : 'category: threw')
    }
  }

  if (plan.override) {
    await overrideRouting(complaint.id, admin, catalogue, rng, tally)
  }

  if (plan.breach) {
    tally.leftToBreach++
    return schedule
  }

  const officerId = complaint.assignedOfficer?.id
  const officer = officerId != null ? catalogue.officers.get(officerId) : undefined
  if (!officer) {
    note(tally, 'no officer holds this complaint')
    return schedule
  }

  const session = await officerSession(officer, options)
  if (!session) {
    note(tally, 'officer could not sign in')
    return schedule
  }

  // Nothing beyond routing has happened yet in simulated time — the case was
  // filed too recently. It sits on the officer's desk, which is correct.
  if (!plan.timeline.allottedAt) return schedule

  const sectorId = complaint.sector?.id ?? null
  const code = await allot(complaint.id, sectorId, session, catalogue, officer, rng, tally)
  if (!code) return schedule
  tally.allotted++

  // The crew has not reported back yet in simulated time.
  if (!plan.timeline.submittedAt) return schedule

  // Send the crew out, possibly twice if the officer refuses the first attempt.
  if ((await submitWork(code, options.baseUrl, rng, tally)) !== 'accepted') return schedule
  tally.submitted++

  if (plan.rejectOnce && plan.timeline.resubmittedAt) {
    try {
      await session.post(`/officer/complaints/${complaint.id}/verify`, {
        accept: false,
        note: rng.pick(REJECTION_NOTES),
      })
      tally.rejected++
    } catch (error) {
      note(tally, error instanceof ApiError ? `reject: ${error.status}` : 'reject: threw')
      return schedule
    }

    // Refusing the work reopens the job, so the crew needs a fresh code.
    const next = await allot(complaint.id, sectorId, session, catalogue, officer, rng, tally)
    if (!next) return schedule
    code.value = next.value
    if ((await submitWork(code, options.baseUrl, rng, tally)) !== 'accepted') return schedule
    tally.submitted++
  }

  /*
   * Who decides that the work is done.
   *
   * Both routes out of AWAITING_VERIFICATION need the complaint to still be in
   * it, so they are alternatives, not a sequence — the citizen answering and
   * the officer inspecting are two ways the same question gets settled, and
   * whichever happens first ends it. Modelling them in order was wrong, and the
   * API said so: every confirmation came back 422 because the officer had
   * already moved the complaint to RESOLVED.
   *
   * The third outcome is nobody answering at all. Those are left deliberately
   * untouched — deciding them is the verification sweep's entire job, and it
   * cannot demonstrate that if the simulator answers on the citizen's behalf.
   */
  // Still awaiting an answer as of now.
  if (!plan.timeline.settledAt) {
    tally.leftUnanswered++
    return schedule
  }

  const settledBy = rng.weighted([
    { value: 'citizen' as const, weight: plan.confirms ? 46 : 0 },
    { value: 'officer' as const, weight: 39 },
    { value: 'nobody' as const, weight: 15 },
  ])

  if (settledBy === 'citizen') {
    try {
      await citizen.post(`/complaints/${complaint.id}/confirm`, {
        confirmed: true,
        rating: rng.weighted([
          { value: 5, weight: 3 },
          { value: 4, weight: 4 },
          { value: 3, weight: 2 },
          { value: 2, weight: 1 },
          { value: 1, weight: 1 },
        ]),
      })
      tally.confirmed++
      tally.resolved++
      schedule.resolvedAt = plan.timeline.settledAt ?? null
      schedule.closedAt = plan.timeline.closedAt ?? null
    } catch (error) {
      note(tally, error instanceof ApiError ? `confirm: ${error.status}` : 'confirm: threw')
    }
    return schedule
  }

  if (settledBy === 'officer') {
    try {
      await session.post(`/officer/complaints/${complaint.id}/verify`, { accept: true })
      tally.resolved++
      schedule.resolvedAt = plan.timeline.settledAt ?? null
    } catch (error) {
      note(tally, error instanceof ApiError ? `verify: ${error.status}` : 'verify: threw')
    }
    return schedule
  }

  tally.leftUnanswered++
  return schedule
}

/** A mutable holder, because a rejected job gets a second code. */
interface Code {
  value: string
}

async function allot(
  complaintId: number,
  sectorId: number | null,
  officerSession: Session,
  catalogue: Catalogue,
  officer: Officer,
  rng: Rng,
  tally: Tally,
): Promise<Code | null> {
  let crew = catalogue.crewByOfficer.get(officer.id)
  if (!crew) {
    try {
      const listed = await officerSession.get<{ items?: CrewMember[] } | CrewMember[]>('/crew')
      crew = Array.isArray(listed) ? listed : (listed.items ?? [])
    } catch {
      crew = []
    }
    catalogue.crewByOfficer.set(officer.id, crew)
  }

  const eligible = crew.filter((c) => sectorId == null || c.sector?.id === sectorId)
  const chosen = eligible.length > 0 ? rng.pick(eligible) : null

  try {
    const order = await officerSession.post<{ code: string }>('/crew/work-orders', {
      complaintId,
      crewId: chosen?.id ?? null,
      instructions: 'Attend and report with a photograph once done.',
    })
    return { value: order.code }
  } catch (error) {
    note(tally, error instanceof ApiError ? `allot: ${error.status}` : 'allot: threw')
    return null
  }
}

/**
 * A crew member reports the job done.
 *
 * No session at all: the code is the credential, which is the whole design of
 * the field surface. The simulator opens it first, exactly as a phone would,
 * so the work order records that it was opened before it was submitted.
 */
/**
 * What became of a field submission.
 *
 * `refused` is not an error. The proof checks score every submission and reject
 * anything under 35, which leaves the work order open and the complaint still
 * IN_PROGRESS — so the officer has nothing to inspect, and asking them to
 * inspect it returns 400. Treating a refusal as success is what produced that
 * error in the first run.
 */
type Submission = 'accepted' | 'refused' | 'failed'

async function submitWork(
  code: Code,
  baseUrl: string,
  rng: Rng,
  tally: Tally,
): Promise<Submission> {
  const anonymous = new Session(baseUrl, 'crew')

  // A real photograph, not a note. `services/verification.ts` scores the proof
  // and rejects anything under 35, which sends the job back rather than moving
  // the complaint on — so a note-only submission would leave every case stuck
  // at IN_PROGRESS and the officer would never inspect anything.
  const form = new FormData()
  form.append('note', rng.pick(CREW_NOTES))
  form.append('latitude', String(rng.float(28.49, 28.63)))
  form.append('longitude', String(rng.float(77.27, 77.42)))

  const photo = syntheticPhoto(rng.int(1, 2_000_000_000))
  form.append('files', new Blob([photo], { type: 'image/png' }), 'work-done.png')

  try {
    await anonymous.get(`/work/${code.value}`)
    const result = await anonymous.request<{ accepted: boolean; score: number }>(
      'POST',
      `/work/${code.value}/submit`,
      form,
    )
    if (!result.accepted) {
      tally.proofRefused++
      return 'refused'
    }
    return 'accepted'
  } catch (error) {
    if (error instanceof ApiError && error.body.includes('Too many attempts')) {
      tally.rateLimited++
      note(tally, 'submit: rate limited')
    } else {
      note(tally, error instanceof ApiError ? `submit: ${error.status}` : 'submit: threw')
    }
    return 'failed'
  }
}

/**
 * Move a complaint away from where GCCE sent it.
 *
 * Done through the console rather than the officer's own desk, because there is
 * no officer-facing re-routing endpoint — a gap recorded in pending-work.md.
 * The reason is drawn from a fixed list so it aggregates; free text would not.
 */
async function overrideRouting(
  complaintId: number,
  admin: Session,
  catalogue: Catalogue,
  rng: Rng,
  tally: Tally,
): Promise<void> {
  try {
    const candidates = await admin.get<{ items?: { id: number }[] }>(
      `/console/complaints/${complaintId}/candidates`,
    )
    // Ranked best-fit first, so skipping the head is what makes this an
    // override rather than a re-confirmation of GCCE's own choice.
    const options = candidates.items ?? []
    if (options.length < 2) return

    await admin.post(`/console/complaints/${complaintId}/assign`, {
      officerId: rng.pick(options.slice(1)).id,
      reason: rng.pick(OVERRIDE_REASONS),
    })
    tally.overridden++
  } catch (error) {
    note(tally, error instanceof ApiError ? `override: ${error.status}` : 'override: threw')
  }
}

/**
 * Remove the complaints a previous simulation created.
 *
 * `--seed` only reproduces a run if it starts from the same state, and running
 * the simulator twice without this leaves the second run's traffic piled on top
 * of the first — same seed, different database, different log. So determinism
 * is a property of `--reset --seed N`, not of `--seed N` alone.
 *
 * Scoped by the synthetic residents' email domain, so seeded demo data and real
 * staff are untouched. The check is on the address rather than on a date range,
 * so a mistimed run can never take out anything that was not generated here.
 *
 * **Two things are deliberately NOT deleted, and both for the same reason.**
 *
 * Audit events: they are hash-chained, and removing rows from the middle of a
 * chain is exactly what `verifyChain` exists to detect. The trail keeps entries
 * for complaints that no longer exist, which is correct for an append-only log —
 * the record that something happened outlives the record itself.
 *
 * The synthetic residents themselves: deleting a user silently breaks the audit
 * chain. `AuditEvent.actorId` is `onDelete: SetNull`, and `actorId` is one of
 * the fields the hash covers — so removing an account rewrites the hashed
 * content of every entry that account ever produced, and every one of them
 * stops verifying. The first version of this function deleted the residents and
 * broke 273 entries doing it. The accounts are therefore kept and reused across
 * runs, which also makes the emails stable and the run more reproducible, not
 * less. The underlying schema defect is recorded in docs/pending-work.md — it
 * is not specific to the simulator, and deleting any real user would do the
 * same thing.
 */
async function resetPreviousRun(prisma: PrismaClient): Promise<void> {
  const residents = await prisma.user.findMany({
    where: { email: { startsWith: SIM_EMAIL_PREFIX, endsWith: SIM_EMAIL_DOMAIN } },
    select: { id: true },
  })
  if (residents.length === 0) {
    console.log('reset: nothing from a previous run to clear')
    return
  }

  const ids = residents.map((r) => r.id)
  const complaints = await prisma.complaint.findMany({
    where: { citizenId: { in: ids } },
    select: { id: true },
  })
  const complaintIds = complaints.map((c) => c.id)

  // Children first: most cascade from Complaint, but the ones that hang off a
  // work order do not, and a foreign key error halfway through a reset leaves
  // a database nobody can reason about.
  const orders = await prisma.workOrder.findMany({
    where: { complaintId: { in: complaintIds } },
    select: { id: true },
  })
  const orderIds = orders.map((o) => o.id)

  await prisma.$transaction([
    prisma.workFile.deleteMany({ where: { submission: { workOrderId: { in: orderIds } } } }),
    prisma.workSubmission.deleteMany({ where: { workOrderId: { in: orderIds } } }),
    prisma.verification.deleteMany({ where: { workOrderId: { in: orderIds } } }),
    prisma.workOrder.deleteMany({ where: { id: { in: orderIds } } }),
    prisma.escalation.deleteMany({ where: { complaintId: { in: complaintIds } } }),
    prisma.complaintStatusHistory.deleteMany({ where: { complaintId: { in: complaintIds } } }),
    prisma.complaintSupport.deleteMany({ where: { complaintId: { in: complaintIds } } }),
    prisma.notification.deleteMany({ where: { userId: { in: ids } } }),
    prisma.complaint.deleteMany({ where: { id: { in: complaintIds } } }),
  ])

  console.log(
    `reset: cleared ${complaintIds.length} simulated complaints; ` +
      `${ids.length} residents and all audit entries kept (deleting either breaks the hash chain)`,
  )
}

// ---------------------------------------------------------------------------
// The run
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const options = parseOptions(process.argv.slice(2))
  assertTimeTravelAllowed()
  await waitForApi(options.baseUrl)

  const rng = new Rng(options.seed)
  const prisma = new PrismaClient()

  console.log('--- DRISHTI-G traffic simulation ---')
  console.log(
    `${options.days} days at ~${options.perDay}/day, seed ${options.seed}, ` +
      `breach ${(options.breachRate * 100).toFixed(0)}%, override ${(options.overrideRate * 100).toFixed(0)}%`,
  )

  const admin = new Session(options.baseUrl, 'Super Admin')
  await admin.post('/auth/login', {
    email: 'admin@drishti.gov.in',
    password: options.password,
  })

  if (options.reset) await resetPreviousRun(prisma)

  const catalogue = await loadCatalogue(admin)
  console.log(`authority: ${catalogue.officers.size} section officers, ${catalogue.units.length} units`)

  const citizens = await registerCitizens(options, rng, catalogue.units)
  console.log(`registered ${citizens.length} synthetic residents`)

  const tally: Tally = {
    filed: 0,
    routed: 0,
    allotted: 0,
    submitted: 0,
    rejected: 0,
    resolved: 0,
    confirmed: 0,
    overridden: 0,
    categoryCorrected: 0,
    categoryConfirmed: 0,
    leftToBreach: 0,
    leftUnanswered: 0,
    proofRefused: 0,
    rateLimited: 0,
    failures: new Map(),
  }

  const escalationWatermark =
    (await prisma.escalation.aggregate({ _max: { id: true } }))._max.id ?? 0
  const breachTimes = new Map<number, Date>()
  const truth: GroundTruth[] = []

  const now = Date.now()
  const start = now - options.days * DAY
  let day = 0

  for (; day < options.days; day++) {
    const dayStart = start + day * DAY
    // Weekends are quieter, and a fifth of days carry a burst — a storm, a
    // festival, a collection truck that did not run. Bursts are what give the
    // clustering engine something to find.
    const weekday = new Date(dayStart).getDay()
    const weekendFactor = weekday === 0 || weekday === 6 ? 0.55 : 1
    const burst = rng.chance(0.18) ? rng.float(1.8, 3.4) : 1
    const arrivals = rng.poisson(options.perDay * weekendFactor * burst)

    for (let i = 0; i < arrivals; i++) {
      // Complaints arrive across the working day, not at midnight.
      const filedAt = new Date(dayStart + rng.float(7, 21) * HOUR)
      const casePlan = plan(rng, filedAt, options, now)
      const schedule = await runCase(
        casePlan,
        rng.pick(citizens),
        admin,
        catalogue,
        options,
        rng,
        tally,
        truth,
      )
      if (!schedule) continue

      await reschedule(prisma, schedule)
      if (casePlan.breach && schedule.slaDueAt) {
        breachTimes.set(schedule.complaintId, new Date(schedule.slaDueAt.getTime() + 2 * HOUR))
      }
    }

    if (day % 30 === 29) {
      process.stdout.write(`  ...${day + 1} days simulated, ${tally.filed} complaints filed\n`)
    }
  }

  // --- The engines that run on a timer -------------------------------------
  //
  // Run after the traffic rather than during it: every case has been backdated
  // by now, so the complaints meant to breach genuinely are overdue relative to
  // real time and the sweep picks them up for real reasons.

  /*
   * Write the ground truth before anything else, so a run that fails during the
   * sweeps still leaves usable labels for what it did file.
   */
  const truthPath = path.resolve(process.cwd(), '../research/data/sim-labels.csv')
  await mkdir(path.dirname(truthPath), { recursive: true })
  await writeFile(
    truthPath,
    ['reference_no,true_category', ...truth.map((t) => `${t.referenceNo},"${t.category}"`)].join(
      LINE_END,
    ) + LINE_END,
    'utf8',
  )
  console.log(`wrote ${truth.length} ground-truth labels to research/data/sim-labels.csv`)

  console.log('running the scheduled sweeps')

  /*
   * The history watermark is taken *here*, not before the traffic.
   *
   * Every row the run itself wrote is already on its case's simulated timeline;
   * only what the sweeps write from this point on is stamped with real `now()`
   * and needs moving. Taking the watermark at the top of the run instead made
   * "newer than the watermark" mean "everything", and the sweep pass redated the
   * entire log onto breach times — which put GCCE routing decisions a day and a
   * half into the future.
   */
  const watermarks = {
    escalationId: escalationWatermark,
    historyId:
      (await prisma.complaintStatusHistory.aggregate({ _max: { id: true } }))._max.id ?? 0,
  }

  // Every sweep runs before anything is rescheduled. Rescheduling in the middle
  // left whatever ran afterwards stamped at today.
  const escalations: { escalated?: number }[] = []
  for (let pass = 0; pass < 3; pass++) {
    escalations.push(await admin.post('/admin/escalations/sweep'))
  }
  const clustering = await admin.post<{ clustered?: number; groups?: number }>(
    '/admin/sweeps/clustering',
  )
  const verification = await admin.post<{ closed?: number; flagged?: number }>(
    '/admin/sweeps/verification',
  )

  const moved = await rescheduleSweepOutput(prisma, watermarks, (id) => breachTimes.get(id) ?? null)

  // Escalation hands the next layer a deadline starting at real `now`, which is
  // correct in production and leaves a simulated register with nothing overdue.
  const deadlines = await repairEscalatedDeadlines(
    prisma,
    (unitId, departmentId) => org.slaHoursFor(prisma, { unitId, departmentId }),
    escalationWatermark,
  )

  // Risk last, so GRIE scores the register as it finally stands.
  const risk = await admin.post<{ recomputed?: unknown }>('/risk/recompute')

  // --- What happened -------------------------------------------------------

  const [complaints, statusRows, escalationCount, clusters, flags, breached, chain] =
    await Promise.all([
      prisma.complaint.count(),
      prisma.complaintStatusHistory.count(),
      prisma.escalation.count({ where: { id: { gt: escalationWatermark } } }),
      prisma.grievanceCluster.count(),
      prisma.riskFlag.count(),
      prisma.complaint.count({ where: { slaDueAt: { lt: new Date() }, resolvedAt: null } }),
      admin.get<{ valid: boolean; checked: number }>('/admin/audit/verify'),
    ])

  console.log('\n--- simulation summary ---')
  const row = (label: string, value: string | number) =>
    console.log(`  ${label.padEnd(34)}${value}`)

  row('complaints filed', tally.filed)
  row('routed to an officer', tally.routed)
  row('work orders issued', tally.allotted)
  row('crew submissions', tally.submitted)
  row('sent back by the officer', tally.rejected)
  row('resolved', tally.resolved)
  row('confirmed by the citizen', tally.confirmed)
  row('category confirmed by citizen', tally.categoryConfirmed)
  row('category corrected by citizen', tally.categoryCorrected)
  row('routing overridden', tally.overridden)
  row('left to breach deliberately', tally.leftToBreach)
  row('awaiting an answer nobody gave', tally.leftUnanswered)
  row('proof refused by the checks', tally.proofRefused)
  console.log()
  row('escalations fired', escalationCount)
  // The sweep also picks up complaints that were already overdue before this
  // run — seed data, or an earlier simulation. Those are not on any simulated
  // timeline, so they keep their real timestamps and are not counted here.
  row('  of those, on simulated cases', moved.escalations)
  row('  sweep history rows redated', moved.history)
  row('  deadlines put back on the clock', deadlines.repaired)
  row('  of those, now genuinely overdue', deadlines.nowOverdue)
  row('clusters in the database', clusters)
  row('GRIE flags raised', flags)
  row('currently overdue and open', breached)
  console.log()
  row('complaints in the database', complaints)
  row('status-history rows', statusRows)
  row('audit chain', chain.valid ? `intact (${chain.checked} entries)` : 'BROKEN')

  if (tally.failures.size > 0) {
    console.log('\n  requests that did not succeed:')
    for (const [reason, count] of [...tally.failures].sort((a, b) => b[1] - a[1])) {
      console.log(`    ${String(count).padStart(5)}  ${reason}`)
    }
  }

  if (tally.rateLimited > 0) {
    console.error(
      `\n${tally.rateLimited} field submissions were refused by the rate limiter on /work.\n` +
        'That limiter is correct in production — the crew surface is unauthenticated and\n' +
        'public — but every simulated crew member shares one IP, so a run of any size\n' +
        'trips it within the first minute and the register fills with jobs nobody ever\n' +
        'reported done. Restart the API with SIM_RELAX_RATE_LIMIT=1 and run again.',
    )
    process.exitCode = 1
  }

  if (!chain.valid) {
    console.error(
      '\nThe audit chain does not verify. Rewriting timestamps must never break it — ' +
        'the hash covers action, actor, entity, payload and the previous hash, not time. ' +
        'Investigate before using this data.',
    )
    process.exitCode = 1
  }

  console.log(
    `\nThis data is SIMULATED. It may train models and fill screens; it is not evidence.\n` +
      `Reproduce it exactly with --seed ${options.seed}.`,
  )

  await prisma.$disconnect()
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
